spring:
  application:
    name: music-recommend
  main:
    allow-bean-definition-overriding: true
  config:
    import:
      - nacos:music-recommend.yml
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: music
      config:
        server-addr: 127.0.0.1:8848
        namespace: music
#  profiles:
#    active:
#      - dev
server:
  servlet:
    context-path: /music-recommend
  port: 9019
mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.music.player.*.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false


logging:
  file:
    path: /Users/shenjia/logs/music/music-recommend
    name: ${spring.application.name}
  config: classpath:log4j2-spring.xml